// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// Data fetching
export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCESSFUL = 'FETCH_DATA_SUCCESSFUL'
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED'
export const RESET_DATA = 'RESET_DATA'

// Questions
export const NEW_QUESTION_START = 'NEW_QUESTION_START'
export const NEW_QUESTION_SUCCESSFUL = 'NEW_QUESTION_SUCCESSFUL'
export const NEW_QUESTION_FAILED = 'NEW_QUESTION_FAILED'

// Answers
export const SAVE_ANSWER_START = 'SAVE_ANSWER_START'
export const SAVE_ANSWER_SUCCESSFUL = 'SAVE_ANSWER_SUCCESSFUL'
export const SAVE_ANSWER_FAILED = 'SAVE_ANSWER_FAILED'

// Redirection
export const SAVE_REDIRECTION_PATH = 'SAVE_REDIRECTION_PATH'
export const RESET_REDIRECTION_PATH = 'RESET_REDIRECTION_PATH'

// Error
export const CLEAR_ERROR = 'CLEAR_ERROR'