// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// Questions
export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START'
export const FETCH_QUESTIONS_SUCCESSFUL = 'FETCH_QUESTIONS_SUCCESSFUL'
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED'

// Users
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESSFUL = 'FETCH_USERS_SUCCESSFUL'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'