// Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// Questions
export const FETCH_QUESTIONS_SUCCESSFUL = 'FETCH_QUESTIONS_SUCCESSFUL'
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED'